// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPV7OxxhBv8ytGMxLQXALxH08Y1L9MA-0',
    appId: '1:258453212439:web:00a517e856a0e38fc3bb52',
    messagingSenderId: '258453212439',
    projectId: 'safarride-ff41d',
    authDomain: 'safarride-ff41d.firebaseapp.com',
    storageBucket: 'safarride-ff41d.firebasestorage.app',
    measurementId: 'G-QC011FQRV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDykQy_p8ll6dUrMDC6POHWb0Rx2rjwdR0',
    appId: '1:258453212439:android:bccf298be61703aac3bb52',
    messagingSenderId: '258453212439',
    projectId: 'safarride-ff41d',
    storageBucket: 'safarride-ff41d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB855nn2tMxGjZtj3yDuVA_iBmj07wdFjc',
    appId: '1:258453212439:ios:7735709b48583c43c3bb52',
    messagingSenderId: '258453212439',
    projectId: 'safarride-ff41d',
    storageBucket: 'safarride-ff41d.firebasestorage.app',
    iosBundleId: 'com.example.safarride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB855nn2tMxGjZtj3yDuVA_iBmj07wdFjc',
    appId: '1:258453212439:ios:7735709b48583c43c3bb52',
    messagingSenderId: '258453212439',
    projectId: 'safarride-ff41d',
    storageBucket: 'safarride-ff41d.firebasestorage.app',
    iosBundleId: 'com.example.safarride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPV7OxxhBv8ytGMxLQXALxH08Y1L9MA-0',
    appId: '1:258453212439:web:2c1798a8c1073b8ac3bb52',
    messagingSenderId: '258453212439',
    projectId: 'safarride-ff41d',
    authDomain: 'safarride-ff41d.firebaseapp.com',
    storageBucket: 'safarride-ff41d.firebasestorage.app',
    measurementId: 'G-0VNLR9DVLD',
  );
}
